title: Cadence Teach Back
remote_theme: ronv/colorie

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

navigation:
  - title: About Me
    url: /aboutme/
  - title: Feedback
    url: /feedback/
  - title: README
    url: /readme/
  - title: Solution
    url: /solution/

plugins:
  - jekyll-remote-theme
