title: Cadence Teach Back
remote_theme: pmarsceill/just-the-docs
# # Show navigation links in the header to these pages (must exist at root)
# header_pages:
#   - about.md
#   - feedback.md
#   - readme.md
#   - solution.md

# # Defaults for pages at root, use 'single' layout for simple pages
# defaults:
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: single

# # Optional: enable search in header
# search_enabled: true
