# name: Deploy Docs to GitHub Pages

# on:
#   push:
#     branches: [main]

# permissions:
#   contents: read
#   pages: write
#   id-token: write

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup GitHub Pages
#         uses: actions/configure-pages@v5

#       - name: Clean build directory
#         run: rm -rf _site

#       - name: Build with Jekyll
#         uses: actions/jekyll-build-pages@v1
#         with:
#           source: ./docs
#           destination: ./_site

#       - name: Upload site content
#         uses: actions/upload-pages-artifact@v3
#         with:
#           path: _site

#       - name: Deploy to GitHub Pages
#         uses: actions/deploy-pages@v4

name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # or your desired Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Clean build directory
        run: rm -rf _site

      - name: Build site with Jekyll (no incremental)
        run: bundle exec jekyll build --source ./docs --destination ./_site

      - name: Upload site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
